language: php

php:
  - 7.1
  - 7.2

sudo: false

cache:
  directories:
    - "$HOME/.composer/cache"

before_install:
  - composer validate
  - composer install

script:
  - ./vendor/bin/phpstan analyze --level=7 lib/
  - ./vendor/bin/phpunit
